---
- name: Install npm packages
  community.general.npm:
    path: /var/www/html/quotify
    no_bin_links: true
  become: true

---
- name: npm build
  shell: npm run build
  args:
    chdir: /var/www/html/quotify