---
- name: Install nginx
  apt:
    name: nginx
    state: present

- name: copy nginx config for quotify
  copy:
    src: ./assets/quotify.nginx
    dest: /etc/nginx/sites-available/quotify.nginx

- name: copy ssl key
  file: 
    path: /etc/letsencrypt/live/quotify.strangled.net/
    recurse: true
    state: directory
  copy:
    src: ./assets/privkey.pem
    dest: /etc/letsencrypt/live/quotify.strangled.net/privkey.pem
  copy:
    src: ./assets/fullchain.pem
    dest: /etc/letsencrypt/live/quotify.strangled.net/fullchain.pem

- name: Create symbolic link for quotify enable
  file:
    src: /etc/nginx/sites-available/quotify.nginx
    dest: /etc/nginx/sites-enabled/quotify
    state: link

- name: Remove default site config
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Remove default site enable link
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove default test page
  file:
    path: /var/www/html/index.nginx-debian.html
    state: absent

- name: Copy nginx.conf
  copy:
    src: ./assets/nginx.conf
    dest: /etc/nginx/nginx.conf
    mode: '644'

- name: Reload service nginx
  service:
    name: nginx
    state: reloaded
